### ISSUE TITLE
UserDetailsService is required

### ISSUE THREAD

**Issue by banterCZ** [wultra/powerauth-webflow#1195]
```
2022-12-15 17:00:42.782  INFO 14220 --- [ (self-tuning)'] i.g.s.p.a.w.controller.HomeController    : The /authenticate/continue request succeeded
2022-12-15 17:00:43.242  INFO 14220 --- [ (self-tuning)'] o.s.s.o.p.token.store.JdbcTokenStore     : Failed to find access token
2022-12-15 17:00:53.546 ERROR 14220 --- [ (self-tuning)'] o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: IllegalStateException, UserDetailsService is required.

java.lang.IllegalStateException: UserDetailsService is required.
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$UserDetailsServiceDelegator.loadUserByUsername(WebSecurityConfigurerAdapter.java:470) ~[spring-security-config-5.6.9.jar:5.6.9]
	at org.springframework.security.core.userdetails.UserDetailsByNameServiceWrapper.loadUserDetails(UserDetailsByNameServiceWrapper.java:71) ~[spring-security-core-5.6.9.jar:5.6.9]
	at org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationProvider.authenticate(PreAuthenticatedAuthenticationProvider.java:97) ~[spring-security-web-5.6.9.jar:5.6.9]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182) ~[spring-security-core-5.6.9.jar:5.6.9]
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices.refreshAccessToken(DefaultTokenServices.java:170) ~[spring-security-oauth2-2.5.2.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.refresh.RefreshTokenGranter.getAccessToken(RefreshTokenGranter.java:55) ~[spring-security-oauth2-2.5.2.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:71) ~[spring-security-oauth2-2.5.2.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:42) ~[spring-security-oauth2-2.5.2.RELEASE.jar:na]
	at org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerEndpointsConfigurer$4.grant(AuthorizationServerEndpointsConfigurer.java:587) ~[spring-security-oauth2-2.5.2.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken(TokenEndpoint.java:137) ~[spring-security-oauth2-2.5.2.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_351]
```

**Comment by banterCZ** [comment]
https://github.com/spring-attic/spring-security-oauth/commit/e303652a911cf0168b5be68383ac120c23ec63b3

**Comment by banterCZ** [comment]
https://stackoverflow.com/a/60406379/204950
