### ISSUE TITLE
Cannot read properties of undefined - smsAuthActions.js

### ISSUE THREAD

**Issue by banterCZ** [wultra/powerauth-webflow#1423]
```
smsAuthActions.js:236 Uncaught TypeError: Cannot read properties of undefined (reading 'then')
    at o.value (smsAuthActions.js:236:5)
    at Object.l (react-dom.production.min.js:14:84)
    at f (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at g (react-dom.production.min.js:15:72)
    at it (react-dom.production.min.js:52:170)
    at rt (react-dom.production.min.js:51:255)
    at ot (react-dom.production.min.js:52:334)
    at pt (react-dom.production.min.js:56:10)
    at H (react-dom.production.min.js:287:189)
    at I (react-dom.production.min.js:19:57)
    at Zt (react-dom.production.min.js:70:279)
    at Xt (react-dom.production.min.js:69:102)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Ka (react-dom.production.min.js:122:325)
    at R (react-dom.production.min.js:287:48)
value @ smsAuthActions.js:236
l @ react-dom.production.min.js:14
f @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
g @ react-dom.production.min.js:15
it @ react-dom.production.min.js:52
rt @ react-dom.production.min.js:51
ot @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
H @ react-dom.production.min.js:287
I @ react-dom.production.min.js:19
Zt @ react-dom.production.min.js:70
Xt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ka @ react-dom.production.min.js:122
R @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68
smsAuthActions.js:236 Uncaught TypeError: Cannot read properties of undefined (reading 'then')
    at o.value (smsAuthActions.js:236:5)
    at Object.l (react-dom.production.min.js:14:84)
    at f (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at g (react-dom.production.min.js:15:72)
    at it (react-dom.production.min.js:52:170)
    at rt (react-dom.production.min.js:51:255)
    at ot (react-dom.production.min.js:52:334)
    at pt (react-dom.production.min.js:56:10)
    at H (react-dom.production.min.js:287:189)
    at I (react-dom.production.min.js:19:57)
    at Zt (react-dom.production.min.js:70:279)
    at Xt (react-dom.production.min.js:69:102)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Ka (react-dom.production.min.js:122:325)
    at R (react-dom.production.min.js:287:48)
value @ smsAuthActions.js:236
l @ react-dom.production.min.js:14
f @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
g @ react-dom.production.min.js:15
it @ react-dom.production.min.js:52
rt @ react-dom.production.min.js:51
ot @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
H @ react-dom.production.min.js:287
I @ react-dom.production.min.js:19
Zt @ react-dom.production.min.js:70
Xt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ka @ react-dom.production.min.js:122
R @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68
smsAuthActions.js:236 Uncaught TypeError: Cannot read properties of undefined (reading 'then')
    at o.value (smsAuthActions.js:236:5)
    at Object.l (react-dom.production.min.js:14:84)
    at f (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at g (react-dom.production.min.js:15:72)
    at it (react-dom.production.min.js:52:170)
    at rt (react-dom.production.min.js:51:255)
    at ot (react-dom.production.min.js:52:334)
    at pt (react-dom.production.min.js:56:10)
    at H (react-dom.production.min.js:287:189)
    at I (react-dom.production.min.js:19:57)
    at Zt (react-dom.production.min.js:70:279)
    at Xt (react-dom.production.min.js:69:102)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Ka (react-dom.production.min.js:122:325)
    at R (react-dom.production.min.js:287:48)
value @ smsAuthActions.js:236
l @ react-dom.production.min.js:14
f @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
g @ react-dom.production.min.js:15
it @ react-dom.production.min.js:52
rt @ react-dom.production.min.js:51
ot @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
H @ react-dom.production.min.js:287
I @ react-dom.production.min.js:19
Zt @ react-dom.production.min.js:70
Xt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ka @ react-dom.production.min.js:122
R @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68

```

**Comment by banterCZ** [comment]
Cannot replicate, a false positive when trying to fix a different issue.
