### ISSUE TITLE
Missing lang.json in powerauth-webflow.war

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-webflow#1678]
Following error occurs in WebFlow on client side on branch `1.4.x`:

```
client.js:54 Uncaught TypeError: Cannot read properties of null (reading 'languageList')
    at client.js:54:9
    at client.js:104:89
    at client.js:104:89
```

The root cause is:
```
2024-08-06 13:05:57.985  WARN 40259 --- [io-8080-exec-14] i.g.s.p.app.webflow.i18n.I18NService     : Error occurred while retrieving the language setting 

java.io.FileNotFoundException: URL [classpath:/static/resources/lang.json] cannot be resolved to absolute file path because it does not reside in the file system: classpath:/static/resources/lang.json
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[spring-core-5.3.24.jar:5.3.24]
	at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:164) ~[spring-core-5.3.24.jar:5.3.24]
	at org.springframework.core.io.UrlResource.getFile(UrlResource.java:241) ~[spring-core-5.3.24.jar:5.3.24]
	at io.getlime.security.powerauth.app.webflow.i18n.I18NService.readLanguageSetting(I18NService.java:89) ~[powerauth-webflow-i18n-1.4.2.jar:1.4.2]
	at io.getlime.security.powerauth.app.webflow.controller.HomeController.authenticate(HomeController.java:189) ~[classes/:1.4.2]
```

**Comment by banterCZ** [comment]
Fixed by https://github.com/wultra/powerauth-webflow/pull/1679
