### ISSUE TITLE
500 error occurs when activation is deleted in database

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-webflow#416]
The 500 error is caused by activation deleted in database (not in REMOVED state, but completely missing in database).

Request:
```
[PowerAuth] PA2Client Request
[PowerAuth] - Method: POST
[PowerAuth] - URL: http://160.218.105.105:8080/powerauth-webflow/api/push/device/register/token
[PowerAuth] - Headers: {
    Accept = "application/json";
    "Accept-Language" = en;
    "Content-Type" = "application/json";
    "X-PowerAuth-Token" = ...
```

Response:
```
[PowerAuth] PA2Client Response
[PowerAuth] - URL: http://[hostname]:8080/powerauth-webflow/api/push/device/register/token
[PowerAuth] - Status code: 500
[PowerAuth] - Headers: {
    "Cache-Control" = "no-cache, no-store, max-age=0, must-revalidate";
    Connection = close;
    "Content-Type" = "application/json;charset=UTF-8";
    Date = "Thu, 02 Aug 2018 09:36:18 GMT";
    Expires = 0;
    Pragma = "no-cache";
    "Transfer-Encoding" = Identity;
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = DENY;
    "X-XSS-Protection" = "1; mode=block";
}
[PowerAuth] - Body: {"status":"ERROR","responseObject":{"code":"ERROR_GENERIC","message":"error.unknown"}}
```

Exception:
```
io.getlime.security.powerauth.app.webflow.exception.DefaultExceptionResolver.handleDefaultException Error occurred in Web Flow server
 org.springframework.ws.soap.client.SoapFaultClientException: Token with given token ID does not exist.
	at org.springframework.ws.soap.client.core.SoapFaultMessageResolver.resolveFault(SoapFaultMessageResolver.java:38)
	at org.springframework.ws.client.core.WebServiceTemplate.handleFault(WebServiceTemplate.java:830)
	at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:624)
	at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:390)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:383)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:373)
	at io.getlime.security.powerauth.soap.spring.client.PowerAuthServiceClient.validateToken(PowerAuthServiceClient.java:882)
	at io.getlime.security.powerauth.rest.api.spring.provider.PowerAuthAuthenticationProvider.validateTokenAuthentication(PowerAuthAuthenticationProvider.java:139)
	at io.getlime.security.powerauth.rest.api.spring.provider.PowerAuthAuthenticationProvider.authenticate(PowerAuthAuthenticationProvider.java:81)
	at io.getlime.security.powerauth.rest.api.spring.provider.PowerAuthAuthenticationProvider.validateToken(PowerAuthAuthenticationProvider.java:269)
	at io.getlime.security.powerauth.rest.api.spring.annotation.PowerAuthAnnotationInterceptor.preHandle(PowerAuthAnnotationInterceptor.java:93)
...
```

**Comment by romanstrobl** [comment]
The root cause is present in powerauth-restful-integration:

https://github.com/wultra/powerauth-restful-integration/issues/60
